//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Input Controllers/PlayerCtrls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerCtrls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerCtrls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerCtrls"",
    ""maps"": [
        {
            ""name"": ""CharacterCtrls"",
            ""id"": ""f99c22e0-594c-42a6-ad06-023dab63bba8"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""966a3f04-edd5-442b-85be-c20fcd277bad"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""1e6cba0d-20ba-4949-ab37-0217ad657d6e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""9d57cddf-03aa-418c-acec-9d3606882954"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d05bb625-b10b-44b1-9323-944b1107a4d4"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6100ebd3-0e67-48c5-9035-4c6701e3367f"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a6e321fc-a3d1-4cf9-bcff-54c29c91bc27"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // CharacterCtrls
        m_CharacterCtrls = asset.FindActionMap("CharacterCtrls", throwIfNotFound: true);
        m_CharacterCtrls_Movement = m_CharacterCtrls.FindAction("Movement", throwIfNotFound: true);
        m_CharacterCtrls_Run = m_CharacterCtrls.FindAction("Run", throwIfNotFound: true);
        m_CharacterCtrls_Newaction = m_CharacterCtrls.FindAction("New action", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CharacterCtrls
    private readonly InputActionMap m_CharacterCtrls;
    private List<ICharacterCtrlsActions> m_CharacterCtrlsActionsCallbackInterfaces = new List<ICharacterCtrlsActions>();
    private readonly InputAction m_CharacterCtrls_Movement;
    private readonly InputAction m_CharacterCtrls_Run;
    private readonly InputAction m_CharacterCtrls_Newaction;
    public struct CharacterCtrlsActions
    {
        private @PlayerCtrls m_Wrapper;
        public CharacterCtrlsActions(@PlayerCtrls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_CharacterCtrls_Movement;
        public InputAction @Run => m_Wrapper.m_CharacterCtrls_Run;
        public InputAction @Newaction => m_Wrapper.m_CharacterCtrls_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_CharacterCtrls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CharacterCtrlsActions set) { return set.Get(); }
        public void AddCallbacks(ICharacterCtrlsActions instance)
        {
            if (instance == null || m_Wrapper.m_CharacterCtrlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CharacterCtrlsActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Run.started += instance.OnRun;
            @Run.performed += instance.OnRun;
            @Run.canceled += instance.OnRun;
            @Newaction.started += instance.OnNewaction;
            @Newaction.performed += instance.OnNewaction;
            @Newaction.canceled += instance.OnNewaction;
        }

        private void UnregisterCallbacks(ICharacterCtrlsActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Run.started -= instance.OnRun;
            @Run.performed -= instance.OnRun;
            @Run.canceled -= instance.OnRun;
            @Newaction.started -= instance.OnNewaction;
            @Newaction.performed -= instance.OnNewaction;
            @Newaction.canceled -= instance.OnNewaction;
        }

        public void RemoveCallbacks(ICharacterCtrlsActions instance)
        {
            if (m_Wrapper.m_CharacterCtrlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICharacterCtrlsActions instance)
        {
            foreach (var item in m_Wrapper.m_CharacterCtrlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CharacterCtrlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CharacterCtrlsActions @CharacterCtrls => new CharacterCtrlsActions(this);
    public interface ICharacterCtrlsActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnNewaction(InputAction.CallbackContext context);
    }
}
